config/routes.rb
Rails.application.routes.draw do
  # get 'welcome/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :reminders
  # root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reminder.rb
class Reminder < ApplicationRecord
    validates :title, presence: true
    validates :do_before, presence: true

    def urgent?
       do_before < Date.today + 7.days && completed == false
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
    def index
        @reminders = Reminder.all.order(:do_before)
    end

    def show
        @reminder = Reminder.find(params[:id])
    end

    def edit
        @reminder = Reminder.find(params[:id])
    end

    def new
        @reminder = Reminder.new
    end

    def create
        @reminder =  Reminder.new(params[:reminder].permit(:title, :do_before)) 
       
        @reminder.save
        if @reminder.errors.any?
            render 'new' and return
        else
            # redirect_to reminders_path
        end
    end

    def update
        @reminder = Reminder.find(params[:id])
        @reminder.update(params[:reminder].permit(:title, :do_before, :completed))
        redirect_to reminder_path(@reminder)
    end

    def destroy
        @reminder = Reminder.find(params[:id])
        @reminder.destroy
        redirect_to reminders_path
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @reminders = Reminder.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Workshop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reminders/edit.html.erb
<%= form_for(@reminder) do |form| %>
  <p><%= form.label("title") %></p>
  <p><%= form.text_field("title") %></p>
  <p><%= form.label("do_before") %></p>
  <p><%= form.date_field("do_before") %></p>
  <p><%= form.label("completed") %></p>
  <p><%= form.check_box("completed") %></p>
  <p><%= form.submit %></p>
<% end %>
<p><%= link_to("Back", reminders_path) %></p>

app/views/reminders/index.html.erb
<table class="text-left table">
    <tr>
        <th>Title</th>
        <th>Do before</th>
        <th>Completed?</th>
        <th>Actions</td>
    </tr>
    <% @reminders.each do |reminder| %>
        <tr class="<%= reminder.urgent? ? "danger" : "" %>">
            <td>
                <%= reminder.title %>
            </td>
            <td>
                <%= reminder.do_before.to_date %>
            </td>
            <td>
                <%= reminder.completed %>
            </td>
            <td>
                <%= link_to 'Show', reminder_path(reminder.id) %>
                <%= link_to 'Edit', edit_reminder_path(reminder.id) %>
                <%= link_to 'Destroy', reminder, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </td>
        </tr>
    <% end %>
</table>
<%= link_to 'New', new_reminder_path, class: 'btn btn-success d-block' %>

<a href="<%= image_path 'giraffe.jpg' %>" target="_blank">
    <%= image_tag 'giraffe.jpg', class: 'awesome-image' %>
</a>

app/views/reminders/new.html.erb
<div data-turbo=false>
    <%= form_for(@reminder) do |form| %>
        <div class="form-group">
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
            <p><%= form.label :do_before %></p>
            <p><%= form.date_field :do_before, class: "form-control" %></p>
        </div>
        <p><%= form.submit class: 'btn btn-primary' %></p>
    <% end %>
</div>
<p>
    <% if @reminder.errors.any? %>
        <% @reminder.errors.messages.each do |field, errors| %>
            <p>Field <%= field %> <%= errors.join %></p>
        <% end %>
    <% end %>
</p>
<p><%= link_to("Back", reminders_path) %></p>

app/views/reminders/show.html.erb
<p>Przypomnij o: <%= @reminder.title %></p>
<p>Kiedy?: <%= @reminder.do_before %></p>
<p>
    Zrobione? 
    <%= @reminder.completed ? 'Tak' : 'Nie' %>
</p>

<%= link_to "Back", reminders_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<table>
    <tr>
        <th>Title</th>
        <th>Do before</th>
        <th>Completed?</th>
    </tr>
    <% @reminders.each do |reminder| %>
        <tr>
            <td>
                <%= reminder.title %>
            </td>
            <td>
                <%= reminder.do_before %>
            </td>
            <td>
                <%= reminder.completed %>
            </td>
        </tr>
    <% end %>
</table>